Survival charts don't show p-value whenever any group has less than 10 cases
cBioPortal/cbioportal-frontend pull request #3819
Opened 2021-06-25 17:23 UTC by dippindots

Fix cBioPortal/cbioportal#8719

2021-06-25 17:29 UTC, dippindots commented on src/pages/resultsView/survival/SurvivalChart.tsx
> +            !_.isNil(this.props.pValue) &&
https://lodash.com/docs/4.17.15#isNil

_.isNil(value): Checks if value is null or undefined.

2021-06-25 20:02 UTC, inodb approved these changes
Great, thank you!!

2021-06-28 19:21 UTC, jjgao requested changes
We should add a message about why p-value is not shown.

2021-06-30 18:26 UTC, inodb commented
@dippindots @jjgao maybe we can show the text:

"p-value not shown if <10 samples"

2021-06-30 18:26 UTC, dippindots commented
Thanks @jjgao @inodb for review this! Any suggestions on how to show this message? On our example link, I already see 3 messages on the top...

2021-06-30 23:47 UTC, inodb commented
@dippindots thanks so much! Just realized the samples typo on my end, my bad. Maybe instead of

```
Logrank Test P-Value: N/A (<10 samples)
```

We can do 

```
Logrank Test P-Value: N/A (<10 cases)
```

2021-06-30 23:48 UTC, inodb commented on src/pages/resultsView/survival/SurvivalChart.tsx
> +            return 'N/A (<10 samples)';
```suggestion
            return 'N/A (<10 cases)';
```

2021-07-06 15:46 UTC, inodb commented
Maybe we should write this out a bit more - 

Be careful when interpreting this p-value because group x has less than y samples

2021-07-20 15:41 UTC, dippindots commented
close this until we have better understanding of how to fix this.

2021-07-20 15:41 UTC, closed without merging