Already existing statement has been modified to handle the case menti…
cBioPortal/cbioportal-frontend pull request #4210
Opened 2022-03-23 17:59 UTC by aswin2108

…oned in the issues tab and an extra statement has been used to handle the case where only the last bar of the chart is filtered out
@onursumer 

Describe changes proposed in this pull request:
- First the issue mentioned in the issues tab was handled by modifying the existing statement, 
- and then end case of selecting only the last bar was handled by adding a new `if else` statement.
This PR fixes cBioPortal/cbioportal#9266

## Screenshots
**Before:** 
![image](https://user-images.githubusercontent.com/72661784/159764566-068523e7-b0af-4205-a00c-a28366eb4d31.png)

**After:**
![image](https://user-images.githubusercontent.com/72661784/159764836-32d50048-6878-4a49-bdfe-a97e14c17eec.png)

![image](https://user-images.githubusercontent.com/72661784/159765000-9f13208c-af51-4542-90d8-8990794d7b0e.png)

2022-03-23 19:48 UTC, onursumer requested changes
This breaks some already existing unit test cases. You should be able to fix the issue without introducing new bugs. And ideally we should also add new unit tests for the case you are trying to fix.

```
Summary of all failing tests
 FAIL  src/pages/studyView/StudyViewUtils.spec.tsx (45.768 s)
  ● StudyViewUtils › intervalFiltersDisplayValue › generates display value for filter values with start closed, end open

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      "> 10"
    Received:
      "≥ 10"
    
    Message:
      expected '≥ 10' to equal '> 10'

    Difference:

    - Expected
    + Received

    - > 10
    + ≥ 10

      1424 |                 true
      1425 |             );
    > 1426 |             assert.equal(value, '> 10');
           |                    ^
      1427 |         });
      1428 |
      1429 |         it('generates display value for filter values with start closed, end open, with special values', () => {

      at Object.<anonymous> (src/pages/studyView/StudyViewUtils.spec.tsx:1426:20)

  ● StudyViewUtils › intervalFiltersDisplayValue › generates display value for filter values with start closed, end open, with special values

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      "> 10, NA, REDACTED"
    Received:
      "≥ 10, NA, REDACTED"
    
    Message:
      expected '≥ 10, NA, REDACTED' to equal '> 10, NA, REDACTED'

    Difference:

    - Expected
    + Received

    - > 10, NA, REDACTED
    + ≥ 10, NA, REDACTED

      1433 |                 true
      1434 |             );
    > 1435 |             assert.equal(value, '> 10, NA, REDACTED');
           |                    ^
      1436 |         });
      1437 |
      1438 |         it('generates display value for filter values with special values only', () => {

      at Object.<anonymous> (src/pages/studyView/StudyViewUtils.spec.tsx:1435:20)


Test Suites: 1 failed, 3 skipped, 184 passed, 185 of 188 total
Tests:       2 failed, 13 skipped, 1786 passed, 1801 total
```

2022-03-28 16:48 UTC, onursumer requested changes

2022-03-30 18:08 UTC, onursumer requested changes

2022-03-31 19:42 UTC, onursumer requested changes
Looks better. Can you also add a new test case to cover the bug you are fixing?

2022-03-31 19:42 UTC, onursumer commented on src/pages/studyView/StudyViewUtils.tsx
> +            intervalDisplayValues.push(startText);
Looks better. Can we move this condition directly into `else if (end === undefined)` block?

Something like this:
```suggestion
        } else if (
            end === undefined
        ) {
            if (numericals[0].start === numericals[0].end) {
                intervalDisplayValues.push(`≥ `);
            } else {
                intervalDisplayValues.push(`> `);
            }
            
            intervalDisplayValues.push(startText);
```

2022-04-02 00:23 UTC, onursumer reviewed
Looks good! Can you rebase to the latest master and squash commits to a single commit? (`git rebase -i upstream/master`)

2022-04-02 02:47 UTC, aswin2108 commented on src/pages/studyView/StudyViewUtils.tsx
> +            intervalDisplayValues.push(startText);
Actually, I noticed your suggestion after pushing the test, so just after that itself, I pushed these changes!

2022-04-03 08:54 UTC, aswin2108 commented on src/pages/studyView/StudyViewUtils.tsx
> +            intervalDisplayValues.push(startText);
@onursumer I have squashed and rebased, what to do next?

2022-04-06 00:30 UTC, onursumer approved these changes
Looks good. We may need some manual product testing before merging this PR to make sure that nothing has been accidentally broken.

2022-04-11 07:57 UTC, dippindots approved these changes
Looks good to me from code side. @aswin2108 Thanks for fixing this.

2022-04-14 16:59 UTC, inodb approved these changes
Great work 🏆! Thanks so much for your contribution!

2022-04-14 16:59 UTC, merged