Fix for the bug of default genes of PM.
cBioPortal/cbioportal-frontend pull request #4492
Opened 2023-01-25 19:33 UTC by YusufZiyaOzgul

Fix cBioPortal/cbioportal# (see https://help.github.com/en/articles/closing-issues-using-keywords)

Describe changes proposed in this pull request:
- a
- b

## Checks
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

## Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [Giphy CAPTURE](https://giphy.com/apps/giphycapture) or [Peek](https://github.com/phw/peek)

## Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). It can help to figure out who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them either through slack or by assigning them as a reviewer on the PR

2023-01-25 20:14 UTC, onursumer requested changes
Thanks! This change seems working, we may just want to reuse an existing function inside the new one.

2023-01-25 20:14 UTC, onursumer commented on src/shared/lib/comparison/ComparisonStore.ts
> +            );
Looks like we are already computing this part in the [@computed get alterationEnrichmentRowData](https://github.com/cBioPortal/cbioportal-frontend/blob/6ffbe5e2a41ce6e765f40391fda37fa91c221232/src/shared/lib/comparison/ComparisonStore.ts#L1129) function. We should probably reuse that function here as well.

We may try converting `alterationEnrichmentRowData` to a `readonly` function and awaiting it here.

2023-01-25 21:20 UTC, onursumer requested changes

2023-01-25 21:20 UTC, onursumer commented on src/pages/groupComparison/GroupComparisonPage.tsx
> +                                        .result!
probably safer to return an empty array here
```suggestion
                                        .result || []
```

2023-01-25 21:20 UTC, onursumer commented on src/pages/groupComparison/pathwayMapper/GroupComparisonPathwayMapper.tsx
> +        return this.props.store.alterationEnrichmentRowData.result!.filter(
let's assume that result might be undefined
```suggestion
        return (this.props.store.alterationEnrichmentRowData.result || []).filter(
```

2023-01-27 16:04 UTC, onursumer approved these changes
Looks good. Let's do a squash merge to reduce the number of commit messages.

2023-01-30 20:13 UTC, alisman approved these changes

2023-01-30 21:49 UTC, merged