Fix #11245: Add tooltip to 'Altered group' axis label for box plot statistics
cBioPortal/cbioportal-frontend pull request #5073
Opened 2024-12-23 10:42 UTC by wavehunter1715

Fix cBioPortal/cbioportal#11245

Describe changes proposed in this pull request:
- Added a tooltip to the "Altered group" axis label to display box plot statistics.
- Tooltip content matches the statistical information shown when hovering over the box.

## Checks
- [x] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [x] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

## Any screenshots or GIFs?
Before : 
<img width="1175" alt="Before" src="https://github.com/user-attachments/assets/04f2297f-a572-4c1a-9c67-c7059ad57fd0" />

After :
<img width="1273" alt="After" src="https://github.com/user-attachments/assets/9135c034-9306-4a79-b03e-23abfdae9365" />

## Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). It can help to figure out who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them either through slack or by assigning them as a reviewer on the PR

2024-12-30 19:23 UTC, chandrikarj commented
Hi @inodb, could you pls review and suggest the required changes?

2025-01-03 16:54 UTC, alisman commented
@chandrikarj thanks for this PR and sorry for my tardiness.  I think it would be much preferable to use the model we already have for introducing custom HTML tooltips into Victory plots.  You can see that at work in 
src/shared/components/plots/BoxScatterPlot.tsx ~l164

This avoids leaving React paradigm in the way that you do. 

Let me know if you have any questions.

2025-01-03 16:54 UTC, alisman requested changes
See comment on PR

2025-01-04 07:25 UTC, chandrikarj commented
Thank you @alisman for providing feedback. I’ll look into the implementation again and will try to refactor the code accordingly.

2025-01-27 21:01 UTC, alisman commented
@chandrikarj please reopen PR after my comments are addressed. thank you for your work

2025-01-27 21:01 UTC, closed without merging